#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(ggplot2)

#Load diamonds dataset
data("diamonds")

#simplify dataset by filtering out diamonds of perfect clarity
diamonds <- diamonds[diamonds$clarity == "VS2",]

#Keep only columns of interest
diamonds <- diamonds[,c("price","carat","cut","color")]
diamonds$cut <- factor(diamonds$cut, ordered = F)
diamonds$color <- factor(diamonds$color, ordered = F)

# Define UI for application that draws a histogram
shinyUI(fluidPage(
    
    # Application title
    titlePanel("Diamond Price Estimator"),

    # Sidebar
    sidebarLayout(
        sidebarPanel(
            h3("Please provide the characteristics of your diamond:"),
            sliderInput("Carat",
                        "Carat:",
                        min = min(diamonds$carat),
                        max = max(diamonds$carat),
                        value = median(diamonds$carat)),
            radioButtons("Cut",
                        "Cut:",
                        choices = c("Ideal","Premium","Very Good", "Good", "Fair"),
                        selected ="Ideal"),
            radioButtons("Color",
                        "Color:",
                        choices = c("D","E","F", "G", "H","I","J"),
                        selected ="D")
        ),

        # Show price estimate generated by model based on input characteristics
        mainPanel(
            h3("Estimated price of your diamond in USD:"),
            h5("Price will appear here once the estimator model is loaded"),
            textOutput("text1")
        )
    )
))
